# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2MzLeYUgvaCWVeggIDLZv9D4CRvwHMG

**Standard print() Statements**
"""

#lib/app.py
print("Hello World!")
print("Hello sun!")
print("Hello sky!")

"""**Choosing your own print() Ending**"""

#lib/app.py
print("Hello World!", end="")
print("Hello sun!", end="!!")
print("Hello sky!", end="!!!\n")